name: "Build and validate Go generated SDK"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.21.4'

      - name: Build the SDK
        run: go build ./...
